Controllers/FamilyMemberController.cs
using com.pathshala.Models;
using com.pathshala.Models.Dto;
using com.pathshala.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Person = com.pathshala.Enums.Person;

namespace com.pathshala.Controllers
{
    public class FamilyMemberController : BaseController
    {
        // GET: FamilyMember/{Student ID}
        public ActionResult Index(int id)
        {
            IEnumerable<FamilyMemberStudent> members = from fms in DB.FamilyMemberStudents
                                            where fms.StudentID == id
                                            select fms;
            ViewData.Add("StudentID", id);
            return View(members.ToList());
        }

        // GET: FamilyMember/Create/{Student ID}
        public ActionResult Create(int id)
        {
            FamilyMemberStudentModel fmsm = new FamilyMemberStudentModel();
            
            fmsm.FamilyMemberStudent = new FamilyMemberStudent();
            fmsm.FamilyMemberStudent.StudentID = id;

            fmsm.RelationshipTypes = Utility.getLookupByName("RELATION");

            return View(fmsm);
        }

        // POST: FamilyMember/Create
        [HttpPost]
        public ActionResult Create(FamilyMemberStudentModel model)
        {
            try
            {

                model.FamilyMemberStudent.FamilyMember.Person.PersonType = (int)Person.FamilyMember;

                DB.FamilyMemberStudents.InsertOnSubmit(model.FamilyMemberStudent);

                DB.SubmitChanges();

                return RedirectToAction("Index", new { id = model.FamilyMemberStudent.StudentID});
            }
            catch
            {
                return View();
            }
        }

        // GET: FamilyMember/Edit/5
        public ActionResult Edit(int id)
        {
            FamilyMemberStudentModel fmsm = new FamilyMemberStudentModel();

            fmsm.FamilyMemberStudent = (from fms in DB.FamilyMemberStudents
                                       where fms.ID == id
                                       select fms).SingleOrDefault();

            fmsm.RelationshipTypes = Utility.getLookupByName("RELATION");

            return View(fmsm);

            
        }

        // POST: FamilyMember/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FamilyMemberStudentModel model)
        {
            try
            {
                FamilyMemberStudent fmMemStud = (from fms in DB.FamilyMemberStudents
                                            where fms.ID == id
                                            select fms).SingleOrDefault();

                TryUpdateModel(fmMemStud, "FamilyMemberStudent");
                DB.SubmitChanges();

                return RedirectToAction("Index", new { id = fmMemStud.StudentID });
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/StudentController.cs
using com.pathshala.Models;
using com.pathshala.Models.Dto;
using com.pathshala.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Person = com.pathshala.Enums.Person;

namespace com.pathshala.Controllers
{
    public class StudentController : BaseController
    {
        // GET: Student
        public ActionResult Index()
        {

            IEnumerable<Student> students = from s in DB.Students
                                            select s;

            return View(students.ToList());

        }

        // GET: Student/By/{School ID}
        public ActionResult School(int id)
        {
            IEnumerable<Student> students = from t in DB.Students
                                                   where t.SchoolID == id
                                            select t;

            return View("Index", students.ToList());
        }

        // GET: Student/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            StudentModel model = new StudentModel();
            model.Student = new Student();

            model.Schools = Utility.getSchoolsNameValue();

            return View(model);
        }

        // POST: Student/Create
        [HttpPost]
        public ActionResult Create(StudentModel model)
        {
            try
            {

                model.Student.Person.PersonType = (int)Person.Student;

                DB.Students.InsertOnSubmit(model.Student);

                DB.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int id)
        {
            StudentModel model = new StudentModel();
            model.Student = (from s in DB.Students
                             where s.ID == id
                             select s).FirstOrDefault();

            model.Schools = Utility.getSchoolsNameValue();
            model.Grades = Utility.getGrades();

            return View(model);
        }

        // POST: Student/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, StudentModel model)
        {
            try
            {

                Student student = (from s in DB.Students
                                   where s.ID == id
                                   select s).SingleOrDefault();

                UpdateModel(student, "Student");

                //if (model.GradeStudent.GradeID != null) {
                //    GradeStudent grdStdnt = (from gs in DB.GradeStudents
                //                             where gs.StudentID == id
                //                             select gs).SingleOrDefault();

                //    if (grdStdnt == null)
                //    {
                //        grdStdnt = new GradeStudent();
                //        grdStdnt.GradeID = model.GradeStudent.GradeID;
                //        grdStdnt.StudentID = id;
                //        DB.GradeStudents.InsertOnSubmit(grdStdnt);
                //    }
                //    else {
                //        grdStdnt.GradeID = model.GradeStudent.GradeID;
                //    }

                //   // DB.SubmitChanges();

                //}

                DB.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Student/Create.cshtml
@model com.pathshala.Models.Dto.StudentModel


@{
    ViewBag.Title = "Enroll Student";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Student.Person.FirstName, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Student.Person.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Student.Person.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Student.Person.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Student.Person.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Student.Person.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Student.Person.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Student.Person.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Student.Person.Email, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Student.DateOfBirth, "Date Of Birth", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Student.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Student.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Student.SchoolID, "School", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Student.SchoolID, new SelectList(Model.Schools, "Value", "Name"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Student.SchoolID, "", new { @class = "text-danger" })
        </div>
    </div>






    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
            <a href="/Student" class="btn btn-light active" role="button" aria-pressed="true">Cancel</a>
        </div>
    </div>
</div>
}

Views/Student/Edit.cshtml
@model com.pathshala.Models.Dto.StudentModel


@{
    ViewBag.Title = "Update Student";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Student.Person.FirstName, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Student.Person.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Student.Person.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Student.Person.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Student.Person.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Student.Person.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Student.Person.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Student.Person.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Student.Person.Email, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Student.DateOfBirth, "Date Of Birth", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.TextBoxFor(model => model.Student.DateOfBirth, new { @Value = com.pathshala.Utils.Utility.formatDate(Model.Student.DateOfBirth), @class = "datepicker form-control" })
            @Html.ValidationMessageFor(model => model.Student.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Student.SchoolID, "School", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Student.SchoolID, new SelectList(Model.Schools, "Value", "Name"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Student.SchoolID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Student.GradeID, "Assigned Grade", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Student.GradeID, new SelectList(Model.Grades, "Value", "Name"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Student.GradeID, "", new { @class = "text-danger" })
        </div>
    </div>






    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
            <a href="/Student" class="btn btn-light active" role="button" aria-pressed="true">Cancel</a>
        </div>
    </div>
</div>
}

Views/Student/Index.cshtml
@model IEnumerable<com.pathshala.Models.Student>

@{
    ViewBag.Title = "Students";
}

<div class="row">
    <div class="col-sm">
        <h2>@ViewBag.Title</h2>
    </div>
    <div class="col-sm text-right">
        @Html.ActionLink(" Create New", "Create", null, new { @class = "btn btn-primary" })
    </div>
</div>

<table class="table table-striped">
    <tr>
        <th>
            #
        </th>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            School
        </th>
        <th>
            Grade
        </th>
        <th>
            Date Of Birth
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Person.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Person.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.School.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grade.Lookup.Display)
        </td>
        <td>
            @com.pathshala.Utils.Utility.formatDate(item.DateOfBirth)
        </td>
        <td class="text-right">
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-primary btn-sm" })
            @Html.ActionLink("Families", "Index", "FamilyMember", new { id = item.ID }, new { @class = "btn btn-primary btn-sm" })
        </td>
    </tr>
    }

</table>